name: Docker Build and Publish

on:
  workflow_dispath
  push:
    branches: 
      main
      p7zip
      unarr
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  release:
    types
      - created
  
env:
  # docker.io
  REGISTRY_1: docker.io
  # ghcr.io
  REGISTRY_2: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
      ${{ github.repository_owner }}/${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login against a docker.io registry except on PR
      - name: Login to registry ${{ env.REGISTRY_2 }}
        if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Login against a ghcr.io registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY_1 }}
        if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY_1 }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          tags: |
             ${{ env.REGISTRY_2 }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
             ${{ env.REGISTRY_1 }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
         #   ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
      #  labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
        #https://github.com/docker/build-push-action/issues/301
