# workflow name
name: Docker Build and Publish

# on events
on:
  # manual workflow run
  workflow_dispatch:
  # Sequence of patterns matched against refs/heads
  push:
    branches: 
      # Push events on main branch
      - 'p7zip'
      - 'unarr'
  pull_request:
    branches:
      - 'main'
  release:
    types: [released]

# jobs to run
jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      
      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=branch
            type=ref,prefix={{branch}}-,event=pr
            type=semver,prefix={{branch}}-,pattern={{version}}
            type=semver,prefix={{branch}}-,pattern={{major}}.{{minor}}
            type=semver,prefix={{branch}}-,pattern={{major}}            

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login against a docker.io registry except on PR
      - name: Login to registry Dockerhub
        if: ${{ github.event_name != 'pull_request' && github.ref != 'refs/heads/dev' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Login against a ghcr.io registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry GHCR
        if: ${{ github.event_name != 'pull_request' && github.ref != 'refs/heads/dev' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' && github.ref != 'refs/heads/dev' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
