name: "Hadolint"

# on events
on:
  # manual workflow run
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linter
      - uses hadolint/hadolint-action@v1.5.0
         env:
           error_level: 2
           output_format: tty
