name: Build multi-arch image

on:
  workflow_dispatch:
#  push:
#    branches: '**'
#    paths-ignore:
#      - "**.md"
  pull_request:
    branches: '**'
#    paths-ignore:
#      - "**.md"

jobs:
  build_multiarch:
    runs-on: ubuntu-latest
    permissions:
    contents: read
    packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=branch
            type=ref,prefix={{branch}}-,event=pr
            type=semver,prefix={{branch}}-,pattern={{version}}
            type=semver,prefix={{branch}}-,pattern={{major}}.{{minor}}
            type=semver,prefix={{branch}}-,pattern={{major}}
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to registry Dockerhub
        if: ${{ github.event_name != 'pull_request' && github.ref = 'refs/heads/unarr' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Log into registry GHCR
        if: ${{ github.event_name != 'pull_request' && github.ref != 'refs/heads/unarr' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platform: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' && github.ref = 'refs/heads/unarr' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag your-username/multiarch-example:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
